# Generated by Django 4.2.11 on 2024-05-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatquestion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatquestion',
            constraint=models.UniqueConstraint(fields=('chat', 'question_type'), name='unique_chat_question_type'),
        ),
    ]
