# Generated by Django 4.2.11 on 2024-05-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatquestion_unique_chat_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
